# 🔢 NumPy: The Foundation of Data Science & Machine Learning

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 20px; border-radius: 10px; color: white; text-align: center; margin-bottom: 20px;">
    <h2 style="margin: 0; color: white;">📊 Numerical Python for Scientific Computing</h2>
    <p style="margin: 10px 0 0 0; font-size: 1.1em; color: white;">Master the essential library that powers pandas, scikit-learn, and the entire Python data ecosystem</p>
</div>

---

## 🎯 **What You'll Learn**

<table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
<tr style="background-color: #343a40; color: white;">
<td style="padding: 15px; border: 1px solid #495057; width: 50%; color: white;"><strong style="color: white;">🏗️ Core Concepts</strong><br>• Array creation & manipulation<br>• Indexing & slicing<br>• Data types & attributes</td>
<td style="padding: 15px; border: 1px solid #495057; width: 50%; color: white;"><strong style="color: white;">🧮 Mathematical Operations</strong><br>• Vectorized computations<br>• Universal functions<br>• Statistical analysis</td>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 15px; border: 1px solid #495057; color: white;"><strong style="color: white;">🔧 Data Manipulation</strong><br>• Boolean & fancy indexing<br>• Reshaping & broadcasting<br>• Array stacking & splitting</td>
<td style="padding: 15px; border: 1px solid #495057; color: white;"><strong style="color: white;">🤖 ML Applications</strong><br>• Linear algebra operations<br>• Feature engineering<br>• Data preprocessing</td>
</tr>
</table>

---

## 🚀 **Why NumPy Matters for ML**

> **NumPy is the backbone of the Python scientific computing ecosystem.** Understanding NumPy deeply will make you more effective with pandas, scikit-learn, TensorFlow, PyTorch, and virtually every other data science library.

### 🔑 **Key Benefits:**
- ⚡ **Performance**: 10-100x faster than pure Python
- 🧠 **Vectorization**: Write less code, express more logic
- 🔗 **Interoperability**: Works seamlessly with other libraries
- 📊 **Broadcasting**: Elegant operations on arrays of different shapes

---

In [16]:
##install numpy 
!pip install numpy

# 📦 Installation & Setup

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #27ae60; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">💡 Getting Started:</strong> Let's install NumPy and set up our environment for scientific computing.
</div>

## 🛠️ **Installation Methods**

| Method | Command | Best For |
|--------|---------|----------|
| **pip** | `pip install numpy` | General use |
| **conda** | `conda install numpy` | Anaconda users |
| **pip (Jupyter)** | `!pip install numpy` | Notebook environments |

---

In [3]:
## import numpy 
import numpy as np


# 📚 Import Convention & Getting Started

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #f39c12; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">📝 Convention:</strong> Always import NumPy as <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np</code> - this is the universal standard in the data science community.
</div>

```python
import numpy as np  # The standard way to import NumPy
```

---

In [4]:
##create an array using numpy 

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(np.shape(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


# 🏗️ Array Creation Fundamentals

<div style="background: linear-gradient(90deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🎯 Core Concept:</strong> Everything in NumPy revolves around the <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">ndarray</code> (N-dimensional array) - the fundamental data structure for scientific computing.
</div>

## 🔤 **Basic Array Creation**

### ✨ **From Python Lists**
The most common way to start - converting familiar Python data structures into powerful NumPy arrays.

---

In [5]:
## reshape an array 

arr2=np.array([0,1,2,3,4,5])
arr2.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# 🔄 Array Reshaping & Transformation

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #3498db; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🧩 Key Insight:</strong> Reshaping changes how we view data without changing the underlying data itself - crucial for ML algorithms that expect specific input shapes.
</div>

## 🎨 **Shape Manipulation**

### ⚡ **The Golden Rule**
> **Total elements must remain constant:** `original_shape_product = new_shape_product`

---

In [12]:
# Example: When an array cannot be reshaped

# arr3 has 4 elements.
arr3 = np.array([1, 2, 3, 4])

# Trying to reshape arr3 to shape (1, 9) will raise a ValueError,
# because 1*9=9 elements are required, but arr3 only has 4 elements.

try:
    arr3.reshape(1, 9)
except ValueError as e:
    print("Error:", e)

# Important points about numpy.reshape():
# - The total number of elements must remain the same before and after reshaping.
# - If the requested shape does not match the number of elements, numpy raises a ValueError.
# - Use arr.size to check the number of elements in the array.
# - Reshaping is useful for changing the view of data without copying it.


Error: cannot reshape array of size 4 into shape (1,9)


## ⚠️ **Error Handling & Best Practices**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #e74c3c; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🚨 Common Pitfall:</strong> Understanding when reshaping fails helps prevent bugs in your ML pipeline.
</div>

### 🛡️ **Shape Compatibility Check**
Always verify that your reshape operation is mathematically valid.

---

In [11]:
# Creating Arrays with np.arange()

# np.arange() returns evenly spaced values within a given interval.
# Syntax: np.arange(start, stop, step])
# - start: Start of interval (inclusive). Default is 0.
# - stop: End of interval (exclusive).
# - step: Spacing between values. Default is 1.

# Example 1: Specify start, stop, and step
arr_range_step = np.arange(5, 10, 2)
print("Array with start=5, stop=10, step=2:")
print(arr_range_step)  # Output: [5 7 9]

# Example 2: Only specify start and stop (step defaults to 1)
arr_range_default_step = np.arange(5, 10)
print("\nArray with start=5, stop=10 (default step=1):")
print(arr_range_default_step)  # Output: [5 6 7 8 9]

# Note:
# - The stop value is not included in the result.
# - np.arange() is useful for generating sequences of numbers for indexing, looping, or initializing arrays.

Array with start=5, stop=10, step=2:
[5 7 9]

Array with start=5, stop=10 (default step=1):
[5 6 7 8 9]


# 🎲 Array Generation Functions

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🔧 Pro Tip:</strong> NumPy provides powerful functions to generate arrays without manually typing values - essential for creating test data and initializing ML models.
</div>

## 📈 **Sequential Arrays with `np.arange()`**

### 🎯 **Perfect for Creating Indices & Ranges**
Similar to Python's `range()`, but returns a NumPy array with more flexibility.

| Parameter | Description | Default |
|-----------|-------------|---------|
| `start` | Starting value (inclusive) | 0 |
| `stop` | Ending value (exclusive) | Required |
| `step` | Step size | 1 |

---

In [10]:
# NumPy Array Placeholders

# Create a 1-dimensional array of ones
print("1-dimensional array of ones:")
print(np.ones(5))

# Create a 2-dimensional array of ones
print("\n2-dimensional array of ones:")
print(np.ones((3, 4)))

# Create a 3-dimensional array of zeros
print("\n3-dimensional array of zeros:")
print(np.zeros((2, 3, 4)))

# Create an array filled with a specific value using np.full
print("\nArray filled with 7s (shape 2x3):")
print(np.full((2, 3), 7))


1-dimensional array of ones:
[1. 1. 1. 1. 1.]

2-dimensional array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3-dimensional array of zeros:
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

Array filled with 7s (shape 2x3):
[[7 7 7]
 [7 7 7]]


## 🎭 **Array Placeholders & Initialization**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #95a5a6; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🏗️ Use Case:</strong> Create arrays of specific shapes filled with predetermined values - essential for initializing weights in neural networks and creating masks.
</div>

### 📊 **Common Initialization Patterns**

| Function | Purpose | ML Application |
|----------|---------|----------------|
| `np.zeros()` | All zeros | Initialize biases |
| `np.ones()` | All ones | Create masks, normalize |
| `np.full()` | Specific value | Custom initialization |
| `np.empty()` | Uninitialized (fast) | Temporary arrays |

---

In [13]:
# np.random.rand(): Uniform distribution over [0, 1)
print("Random array with np.random.rand(2, 3):")
print(np.random.rand(2, 3))

# np.random.randn(): Standard normal distribution (mean=0, std=1)
print("\nRandom array with np.random.randn(2, 3):")
print(np.random.randn(2, 3))

# np.random.randint(): Random integers from low (inclusive) to high (exclusive)
print("\nRandom integers with np.random.randint(0, 10, size=(2, 3)):")
print(np.random.randint(0, 10, size=(2, 3)))

Random array with np.random.rand(2, 3):
[[0.29786486 0.83022813 0.45026448]
 [0.54972648 0.87985378 0.5508479 ]]

Random array with np.random.randn(2, 3):
[[-0.47449228  1.19202831 -0.81404651]
 [-0.04242613 -1.8391592  -0.15363949]]

Random integers with np.random.randint(0, 10, size=(2, 3)):
[[1 8 7]
 [5 2 7]]


## 🎰 **Random Number Generation**

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🎯 ML Essential:</strong> Random numbers are crucial for data sampling, weight initialization, train/test splits, and adding noise for regularization.
</div>

### 🎲 **Random Distribution Functions**

| Function | Distribution | Range | Common Use |
|----------|-------------|-------|------------|
| `np.random.rand()` | Uniform | [0, 1) | General sampling |
| `np.random.randn()` | Normal (μ=0, σ=1) | (-∞, +∞) | Weight initialization |
| `np.random.randint()` | Discrete uniform | [low, high) | Index sampling |

---

In [14]:
# NumPy Array Attributes Documentation

arr = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])

# ndim: Number of array dimensions (axes)
print("The dimension of the array is:", arr.ndim)  # Output: 2

# shape: Tuple of array dimensions (rows, columns)
print("The shape of the array is:", arr.shape)  # Output: (2, 5)

# size: Total number of elements in the array
print("The size of the array is:", arr.size)  # Output: 10

# dtype: Data type of array elements
print("The datatype of elements is:", arr.dtype)  # Output: int64 (or platform-dependent)

# itemsize: Size in bytes of each element
print("The size (in bytes) of each element is:", arr.itemsize)

# nbytes: Total bytes consumed by the array
print("The total bytes consumed by the array is:", arr.nbytes)


The dimension of the array is: 2
The shape of the array is: (2, 5)
The size of the array is: 10
The datatype of elements is: int64
The size (in bytes) of each element is: 8
The total bytes consumed by the array is: 80


# 🔍 Array Attributes & Properties

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #3498db; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">📊 Debug Tool:</strong> Understanding array properties is essential for debugging and ensuring your data has the expected structure for ML algorithms.
</div>

## 📏 **Essential Array Attributes**

<table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
<tr style="background-color: #343a40; color: white;">
<th style="padding: 12px; border: 1px solid #495057; text-align: left; color: white;">Attribute</th>
<th style="padding: 12px; border: 1px solid #495057; text-align: left; color: white;">Description</th>
<th style="padding: 12px; border: 1px solid #495057; text-align: left; color: white;">ML Relevance</th>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">.ndim</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Number of dimensions</td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Verify data structure (1D=vector, 2D=matrix)</td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">.shape</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Tuple of array dimensions</td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Check input/output compatibility</td>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">.size</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Total number of elements</td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Memory estimation & data size validation</td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">.dtype</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Data type of elements</td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Precision & memory optimization</td>
</tr>
</table>

---

In [ ]:
# NumPy Vectorized Operations Documentation

# Vectorized operations in NumPy allow you to perform element-wise operations on arrays efficiently,
# without the need for explicit Python loops. This leads to concise, readable, and fast code.

# Example arrays:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# 1. Element-wise Addition
# Adds corresponding elements of arr1 and arr2.
added_array = arr1 + arr2
print("Element-wise addition:", added_array)  # Output: [11 22 33 44 55]

# 2. Element-wise Subtraction
# Subtracts elements of arr1 from arr2.
subtracted_array = arr2 - arr1
print("Element-wise subtraction:", subtracted_array)  # Output: [ 9 18 27 36 45]

# 3. Element-wise Multiplication
# Multiplies corresponding elements.
multiplied_array = arr1 * arr2
print("Element-wise multiplication:", multiplied_array)  # Output: [ 10  40  90 160 250]

# 4. Element-wise Division
# Divides elements of arr2 by arr1.
divided_array = arr2 / arr1
print("Element-wise division:", divided_array)  # Output: [10. 10. 10. 10. 10.]

# 5. Element-wise Exponentiation
# Raises elements of arr1 to the power of arr2.
exp_array = arr1 ** 2
print("Element-wise exponentiation (arr1 squared):", exp_array)  # Output: [ 1  4  9 16 25]

# 6. Universal Functions (ufuncs)
# NumPy provides many mathematical functions that operate element-wise.
sqrt_array = np.sqrt(arr1)
print("Element-wise square root:", sqrt_array)  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]

# 7. Comparison Operations
# Returns boolean arrays.
comparison = arr1 > 3
print("Element-wise comparison (arr1 > 3):", comparison)  # Output: [False False False  True  True]

# Notes:
# - Arrays must have the same shape, or be broadcastable to a common shape.
# - Vectorized operations are much faster than looping over elements in Python.
# - Use vectorized operations for mathematical, logical, and comparison tasks on arrays.


[11 22 33 44 55]
[ 9 18 27 36 45]
[10. 10. 10. 10. 10.]


# ⚡ Vectorized Operations: The NumPy Superpower

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3 style="margin: 0; color: white;">🚀 Performance Revolution</h3>
<p style="margin: 10px 0 0 0; font-size: 1.1em; color: white;">NumPy vectorization: 10-100x faster than Python loops!</p>
</div>

## 🎯 **Why Vectorization Matters**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #27ae60; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">⚡ Speed:</strong> Operations are implemented in C and optimized for performance<br>
<strong style="color: white;">🧹 Clean Code:</strong> Express complex operations in simple, readable syntax<br>
<strong style="color: white;">🔧 Memory Efficient:</strong> Avoids Python loop overhead and temporary variables
</div>

### 📊 **Element-wise Operations**
All standard mathematical operations work element-by-element automatically.

---

In [ ]:
## universal function 

arr=np.array([1,4,9,16,25,36])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))



[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]
[0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]


## 🧮 **Universal Functions (ufuncs)**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #f39c12; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🔬 Definition:</strong> Fast, element-wise functions that operate on arrays without explicit loops - the building blocks of scientific computing.
</div>

### 🎨 **Mathematical Function Categories**

| Category | Functions | Use Cases |
|----------|-----------|-----------|
| **🔢 Basic Math** | `sqrt`, `exp`, `log` | Feature transformations |
| **📐 Trigonometric** | `sin`, `cos`, `tan` | Signal processing, physics |
| **📊 Statistical** | `mean`, `std`, `var` | Data analysis |

---

In [ ]:
## indexing in numpy 

arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])


## suppose i have to retrieve 4

print(arr[0][3])

## suppose i want to retrieve 9,10,14,15

print(arr[1:,3:])


## want to retrive 3,4,8,9,13,14



print(arr[0:,2:4])

4
[[ 9 10]
 [14 15]]
hey
[[ 3  4]
 [ 8  9]
 [13 14]]


# 🎯 Array Indexing & Access Patterns

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🔑 Core Skill:</strong> Mastering indexing is essential for data selection, filtering, and manipulation in ML workflows.
</div>

## 📍 **Multi-dimensional Indexing**

### 🎪 **The Coordinate System**
Think of arrays as coordinate systems where each dimension represents an axis.

| Syntax | Dimension | Description |
|--------|-----------|-------------|
| `arr[i]` | 1D | Single element at index i |
| `arr[i, j]` | 2D | Element at row i, column j |
| `arr[i, j, k]` | 3D | Element at depth i, row j, column k |

---

In [ ]:
## replace the array elements 

arr[0][0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


## ✏️ **Array Modification**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #e74c3c; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">⚠️ Important:</strong> NumPy arrays are mutable - changes affect the original array. This is different from Python strings and tuples.
</div>

### 🔄 **In-place Modifications**
Directly change array values using indexing - useful for data cleaning and preprocessing.

---

In [ ]:
## statistical analysis -> normalization 

arr=np.array([1,2,3,4,5])

## compute mean 
mean =np.mean(arr)
## compute s.d
sd=np.std(arr)


normalized_data=(arr-mean)/sd
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


# 📊 Statistical Analysis & Data Normalization

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🎯 ML Foundation:</strong> Statistical operations and normalization are fundamental preprocessing steps in machine learning pipelines.
</div>

## 📏 **Z-Score Normalization**

### 🧮 **The Formula**
```
normalized_value = (value - mean) / standard_deviation
```

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #27ae60; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">✅ Benefits:</strong><br>
• Centers data around 0<br>
• Scales to unit variance<br>
• Essential for gradient descent algorithms<br>
• Prevents feature dominance in ML models
</div>

---

In [ ]:
## statical data 

## mean 

mean=np.mean(arr)

## median 

median =np.median(arr)

## standard deviation

sd=np.std(arr)

## variance

variance =np.var(arr)


print("mean-> ",mean)
print("median-> ",median)
print("standard deviation-> ",sd)
print("variance-> ",variance)



mean->  3.0
median->  3.0
standard deviation->  1.4142135623730951
variance->  2.0


## 📈 **Comprehensive Statistical Measures**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #3498db; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">📊 Data Exploration:</strong> These statistical measures provide insights into your data distribution and help identify outliers and patterns.
</div>

### 🎯 **Key Statistical Functions**

<table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
<tr style="background-color: #343a40; color: white;">
<th style="padding: 12px; border: 1px solid #495057; color: white;">Measure</th>
<th style="padding: 12px; border: 1px solid #495057; color: white;">Function</th>
<th style="padding: 12px; border: 1px solid #495057; color: white;">Interpretation</th>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">Mean</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.mean()</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Central tendency</td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">Median</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.median()</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Robust central value</td>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">Std Dev</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.std()</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Data spread</td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">Variance</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.var()</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Squared deviation</td>
</tr>
</table>

---

In [ ]:
## logical operation 

data=np.array([1,2,3,4,10,11,12,13,6])
##retrieve data>5


print(data[(data>5) & (data<8)])




[6]


# 🎭 Logical Operations & Boolean Filtering

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🔍 Data Filtering:</strong> Boolean operations are your primary tool for data filtering and conditional selection in ML preprocessing.
</div>

## ⚡ **Boolean Indexing Power**

### 🎯 **Logical Operators**
| Operator | NumPy | Python | Usage |
|----------|-------|---------|-------|
| **AND** | `&` | `and` | Multiple conditions |
| **OR** | `\|` | `or` | Alternative conditions |
| **NOT** | `~` | `not` | Negation |

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #f39c12; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">⚠️ Important:</strong> Use <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">&</code> and <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">|</code> instead of <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">and</code> and <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">or</code> for NumPy arrays. Always wrap conditions in parentheses!
</div>

---

In [ ]:
import numpy as np

arr = np.array([30, 10, 20])
sorted_indices = np.argsort(arr)

print(sorted_indices)  # Output: [1 2 0]
print(arr[sorted_indices])  # Output: [10 20 30]


# 🔍 Sorting & Searching Operations

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🎯 Data Organization:</strong> Sorting and finding extreme values are fundamental operations for data analysis and algorithm optimization.
</div>

## 📊 **Index-based Functions**

### 🥇 **Finding Positions of Extreme Values**
These functions return **indices** rather than values - crucial for maintaining data relationships.

| Function | Purpose | Returns | ML Use Case |
|----------|---------|---------|-------------|
| `np.argsort()` | Sort indices | Array of indices | Ranking, ordering |
| `np.argmin()` | Min index | Single index | Find worst performer |
| `np.argmax()` | Max index | Single index | Find best performer |

---

In [ ]:
arr = np.array([30, 10, 20])
min_index = np.argmin(arr)

print(min_index)  # Output: 1
print(arr[min_index])  # Output: 10


## 📉 **Finding Minimum Values**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #3498db; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🎯 Use Case:</strong> Locate the position of minimum values - essential for finding optimal parameters, worst-case scenarios, or minimum errors.
</div>

---

In [ ]:
arr = np.array([30, 10, 20])
max_index = np.argmax(arr)

print(max_index)  # Output: 0
print(arr[max_index])  # Output: 30


## 📈 **Finding Maximum Values**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #27ae60; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🎯 Use Case:</strong> Identify peak values and their positions - crucial for finding best performance, outliers, or maximum activations in neural networks.
</div>

---

In [ ]:
arr2d = np.array([[10, 50], [30, 20]])

print(np.argmax(arr2d))  # Output: 1 (flattened array: [10, 50, 30, 20] → max at index 1)
print(np.argmax(arr2d, axis=0))  # Output: [1 0]
print(np.argmax(arr2d, axis=1))  # Output: [1 0]


## 🎛️ **Multi-dimensional Operations**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #95a5a6; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🔧 Advanced:</strong> Working with different axes allows you to find extrema along specific dimensions - essential for batch processing in ML.
</div>

### 📊 **Axis Operations**
- `axis=None` (default): Flattened array
- `axis=0`: Along rows (column-wise operation)  
- `axis=1`: Along columns (row-wise operation)

---

In [ ]:
## NumPy’s argmax() (and argmin()) returns the index of the first occurrence of the maximum (or minimum) 
# value when the array is flattened (unless you specify an axis).

## 💡 **Important Behavior Notes**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #f39c12; margin: 10px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🔍 Key Insight:</strong> NumPy's argmax() and argmin() return the index of the <strong style="color: white;">first occurrence</strong> when there are multiple equal extreme values.
</div>

### 🎯 **Tie-Breaking Behavior**
When multiple elements have the same extreme value, NumPy consistently returns the first index encountered.

---

# 🔧 Data Manipulation & Indexing
*The essential skills for accessing and modifying your data - a daily task in ML workflows*

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3 style="margin: 0; color: white;">🎯 Master Data Access Patterns</h3>
<p style="margin: 10px 0 0 0; font-size: 1.1em; color: white;">From basic indexing to advanced boolean filtering - unlock the full power of NumPy data manipulation</p>
</div>

---

## 🎪 **Core Indexing Concepts**

<table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
<tr style="background-color: #343a40; color: white;">
<td style="padding: 15px; border: 1px solid #495057; width: 25%; color: white;"><strong style="color: white;">📍 Basic Indexing</strong><br>Access elements like Python lists<br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">arr[5]</code>, <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">arr[0, 2]</code></td>
<td style="padding: 15px; border: 1px solid #495057; width: 25%; color: white;"><strong style="color: white;">🎭 Boolean Indexing</strong><br>Filter data with conditions<br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">arr[arr > 5]</code></td>
<td style="padding: 15px; border: 1px solid #495057; width: 25%; color: white;"><strong style="color: white;">🎨 Fancy Indexing</strong><br>Use arrays as indices<br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">arr[[1, 4, 6]]</code></td>
<td style="padding: 15px; border: 1px solid #495057; width: 25%; color: white;"><strong style="color: white;">🔄 Reshaping</strong><br>Change array dimensions<br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">arr.reshape()</code>, <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">arr.T</code></td>
</tr>
</table>

---

## 🎯 **Slicing Syntax Reference**

| Syntax | Description | Example |
|--------|-------------|---------|
| `arr[start:stop]` | Basic slice | `arr[1:5]` |
| `arr[start:stop:step]` | With step | `arr[::2]` |
| `arr[:, start:stop]` | All rows, slice cols | `arr[:, 1:3]` |
| `arr[start:stop, :]` | Slice rows, all cols | `arr[1:3, :]` |

---

In [ ]:
# Basic Indexing and Slicing Examples

# Create sample arrays for demonstration
arr_1d = np.array([10, 20, 30, 40, 50, 60])
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8], 
                   [9, 10, 11, 12]])

print("1D Array:", arr_1d)
print("2D Array:")
print(arr_2d)

# 1D Array Indexing
print("\n=== 1D Array Indexing ===")
print("arr_1d[0]:", arr_1d[0])  # First element
print("arr_1d[-1]:", arr_1d[-1])  # Last element
print("arr_1d[2:5]:", arr_1d[2:5])  # Slice from index 2 to 4

# 2D Array Indexing
print("\n=== 2D Array Indexing ===")
print("arr_2d[0, 2]:", arr_2d[0, 2])  # Row 0, Column 2
print("arr_2d[1, -1]:", arr_2d[1, -1])  # Row 1, Last column

# 2D Array Slicing
print("\n=== 2D Array Slicing ===")
print("arr_2d[1:3, :]:")  # Rows 1-2, all columns
print(arr_2d[1:3, :])

print("arr_2d[:, 1:3]:")  # All rows, columns 1-2
print(arr_2d[:, 1:3])

print("arr_2d[0:2, 1:4]:")  # Rows 0-1, columns 1-3
print(arr_2d[0:2, 1:4])

In [ ]:
# Boolean Indexing - Extremely Important for Data Filtering

# Create sample data
data = np.array([1, 5, 8, 3, 12, 7, 9, 2, 15, 6])
matrix = np.array([[10, 25, 5], 
                   [30, 8, 12], 
                   [3, 18, 22]])

print("Original data:", data)
print("Original matrix:")
print(matrix)

# Boolean mask creation
print("\n=== Boolean Mask Creation ===")
mask = data > 5
print("Mask (data > 5):", mask)
print("Elements > 5:", data[mask])

# Alternative direct approach
print("Direct filtering (data > 5):", data[data > 5])

# Multiple conditions
print("\n=== Multiple Conditions ===")
# Elements between 5 and 10
filtered = data[(data > 5) & (data < 10)]
print("Elements between 5 and 10:", filtered)

# Elements less than 3 OR greater than 12
filtered2 = data[(data < 3) | (data > 12)]
print("Elements < 3 OR > 12:", filtered2)

# Boolean indexing with 2D arrays
print("\n=== 2D Boolean Indexing ===")
print("Matrix elements > 15:", matrix[matrix > 15])
print("Matrix elements divisible by 5:", matrix[matrix % 5 == 0])

# Modifying elements using boolean indexing
print("\n=== Modifying with Boolean Indexing ===")
data_copy = data.copy()
data_copy[data_copy > 10] = 999  # Replace all values > 10 with 999
print("After replacing values > 10 with 999:", data_copy)

In [ ]:
# Fancy Indexing - Using Arrays of Indices

# Create sample arrays
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print("Original array:", arr)
print("Original matrix:")
print(matrix)

# Fancy indexing with 1D array
print("\n=== Fancy Indexing 1D ===")
indices = [1, 4, 6, 8]
selected_elements = arr[indices]
print(f"Elements at indices {indices}:", selected_elements)

# Using np.array for indices
indices_array = np.array([0, 2, 5, 7])
print(f"Elements at indices {indices_array}:", arr[indices_array])

# Fancy indexing with 2D array
print("\n=== Fancy Indexing 2D ===")
# Select specific rows
row_indices = [0, 2, 3]
selected_rows = matrix[row_indices]
print(f"Rows {row_indices}:")
print(selected_rows)

# Select specific elements using row and column indices
row_idx = [0, 1, 2, 3]
col_idx = [1, 2, 0, 3]
diagonal_elements = matrix[row_idx, col_idx]
print(f"Elements at positions (0,1), (1,2), (2,0), (3,3):", diagonal_elements)

# Combine fancy indexing with slicing
print("\n=== Combining Fancy Indexing with Slicing ===")
selected_subset = matrix[[0, 2], 1:3]  # Rows 0 and 2, columns 1-2
print("Rows 0,2 and columns 1-2:")
print(selected_subset)

# Fancy indexing for rearranging
print("\n=== Rearranging with Fancy Indexing ===")
reorder_indices = [3, 1, 0, 2]
reordered_matrix = matrix[reorder_indices]
print("Reordered matrix (rows 3,1,0,2):")
print(reordered_matrix)

In [ ]:
# Reshaping Arrays - Changing Shape Without Changing Data

# Create sample arrays
arr_1d = np.arange(12)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("Original 1D array:", arr_1d)
print("Original 2D array:")
print(arr_2d)

# Basic reshaping
print("\n=== Basic Reshaping ===")
reshaped_2d = arr_1d.reshape(3, 4)
print("1D array reshaped to 3x4:")
print(reshaped_2d)

reshaped_3d = arr_1d.reshape(2, 2, 3)
print("1D array reshaped to 2x2x3:")
print(reshaped_3d)

# Using -1 for automatic dimension calculation
print("\n=== Automatic Dimension Calculation ===")
auto_reshape = arr_1d.reshape(4, -1)  # NumPy calculates the second dimension
print("Reshape with automatic dimension (4, -1):")
print(auto_reshape)

auto_reshape2 = arr_1d.reshape(-1, 6)  # NumPy calculates the first dimension
print("Reshape with automatic dimension (-1, 6):")
print(auto_reshape2)

# Flatten arrays
print("\n=== Flattening Arrays ===")
flattened = reshaped_2d.flatten()
print("Flattened 2D array:", flattened)

# Alternative: ravel() - returns a view when possible
raveled = reshaped_2d.ravel()
print("Raveled 2D array:", raveled)

# Transpose operations
print("\n=== Transpose Operations ===")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix:")
print(matrix)

# Method 1: .T attribute
print("Transposed matrix (.T):")
print(matrix.T)

# Method 2: .transpose() method
print("Transposed matrix (.transpose()):")
print(matrix.transpose())

# Method 3: np.transpose() function
print("Transposed matrix (np.transpose()):")
print(np.transpose(matrix))

# Transpose with higher dimensions
print("\n=== 3D Transpose ===")
arr_3d = np.arange(24).reshape(2, 3, 4)
print("3D array shape:", arr_3d.shape)
print("Transposed 3D array shape:", arr_3d.T.shape)

# Custom axis permutation
transposed_custom = np.transpose(arr_3d, (2, 0, 1))
print("Custom transpose (2,0,1) shape:", transposed_custom.shape)

# 📈 Mathematical & Statistical Operations
*NumPy's computational power unleashed - the engine behind scientific computing*

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3 style="margin: 0; color: white;">⚡ Vectorized Performance</h3>
<p style="margin: 10px 0 0 0; font-size: 1.1em; font-weight: bold; color: white;">Fast, element-wise operations that make NumPy 10-100x faster than pure Python</p>
</div>

---

## 🧮 **Universal Functions (ufuncs)**
*Fast, element-wise functions that operate without explicit loops*

### 🎨 **Function Categories**

<table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
<tr style="background-color: #343a40; color: white;">
<th style="padding: 12px; border: 1px solid #495057; text-align: left; color: white;">Category</th>
<th style="padding: 12px; border: 1px solid #495057; text-align: left; color: white;">Functions</th>
<th style="padding: 12px; border: 1px solid #495057; text-align: left; color: white;">ML Applications</th>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">🔢 Arithmetic</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">+, -, *, /, **</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Feature scaling, transformations</td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">📐 Trigonometric</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">sin(), cos(), tan()</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Signal processing, feature engineering</td>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 10px; border: 1px solid #495057; color: white;"><strong style="color: white;">📊 Exponential/Log</strong></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;"><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">exp(), log(), log10()</code></td>
<td style="padding: 10px; border: 1px solid #495057; color: white;">Activation functions, data transforms</td>
</tr>
</table>

---

## 📊 **Aggregation Functions**
*Summarize data across entire arrays or specific axes*

### 🎯 **Essential Statistics**

| Function | Purpose | ML Relevance |
|----------|---------|--------------|
| **📊 `np.sum()`** | Total of elements | Feature sums, batch totals |
| **📈 `np.mean()`** | Average value | Central tendency, normalization |
| **📏 `np.std()`** | Standard deviation | Data spread, normalization |
| **🎯 `np.min()`, `np.max()`** | Extreme values | Data range, clipping |
| **🔍 `np.argmin()`, `np.argmax()`** | Indices of extrema | Finding best/worst performers |

---

In [ ]:
# Universal Functions (ufuncs) - Fast Element-wise Operations

# Create sample data
arr = np.array([1, 4, 9, 16, 25])
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
data = np.array([[1, 2, 3], [4, 5, 6]])

print("Sample array:", arr)
print("Angles array:", angles)
print("2D data:")
print(data)

# Arithmetic operations
print("\n=== Arithmetic Operations ===")
print("Square root:", np.sqrt(arr))
print("Square:", np.power(arr, 2))
print("Cube:", arr ** 3)
print("Reciprocal:", 1 / arr)

# Exponential and logarithmic functions
print("\n=== Exponential & Logarithmic ===")
small_arr = np.array([1, 2, 3, 4])
print("Original:", small_arr)
print("Exponential (e^x):", np.exp(small_arr))
print("Natural log:", np.log(small_arr))
print("Log base 10:", np.log10(small_arr))
print("Log base 2:", np.log2(small_arr))

# Trigonometric functions
print("\n=== Trigonometric Functions ===")
print("Angles (radians):", angles)
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

# Convert degrees to radians
degrees = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(degrees)
print("Degrees:", degrees)
print("Converted to radians:", radians)
print("Sine of degrees:", np.sin(radians))

# Rounding functions
print("\n=== Rounding Functions ===")
decimal_arr = np.array([1.234, 2.678, 3.999, 4.001])
print("Original decimals:", decimal_arr)
print("Round to nearest:", np.round(decimal_arr))
print("Floor (round down):", np.floor(decimal_arr))
print("Ceiling (round up):", np.ceil(decimal_arr))
print("Truncate:", np.trunc(decimal_arr))

# Comparison and logical operations
print("\n=== Comparison Operations ===")
arr1 = np.array([1, 5, 3, 8, 2])
arr2 = np.array([2, 4, 3, 7, 9])
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Maximum of each pair:", np.maximum(arr1, arr2))
print("Minimum of each pair:", np.minimum(arr1, arr2))
print("Absolute difference:", np.abs(arr1 - arr2))

In [ ]:
# Aggregation Functions - Summarizing Data

# Create sample data
data_1d = np.array([10, 25, 30, 15, 40, 35, 20])
data_2d = np.array([[10, 20, 30], 
                    [40, 50, 60], 
                    [70, 80, 90]])

print("1D Data:", data_1d)
print("2D Data:")
print(data_2d)

# Basic aggregation functions
print("\n=== Basic Aggregations (1D) ===")
print("Sum:", np.sum(data_1d))
print("Mean:", np.mean(data_1d))
print("Median:", np.median(data_1d))
print("Standard Deviation:", np.std(data_1d))
print("Variance:", np.var(data_1d))
print("Minimum:", np.min(data_1d))
print("Maximum:", np.max(data_1d))
print("Range (max - min):", np.ptp(data_1d))  # Peak to peak

# Index-based functions
print("\n=== Index-based Functions ===")
print("Index of minimum:", np.argmin(data_1d))
print("Index of maximum:", np.argmax(data_1d))
print("Value at min index:", data_1d[np.argmin(data_1d)])
print("Value at max index:", data_1d[np.argmax(data_1d)])

# Percentiles and quantiles
print("\n=== Percentiles & Quantiles ===")
print("25th percentile:", np.percentile(data_1d, 25))
print("50th percentile (median):", np.percentile(data_1d, 50))
print("75th percentile:", np.percentile(data_1d, 75))
print("Multiple percentiles:", np.percentile(data_1d, [25, 50, 75]))

# 2D Array aggregations with axis parameter
print("\n=== 2D Aggregations with Axis ===")
print("Sum of all elements:", np.sum(data_2d))
print("Sum along axis 0 (columns):", np.sum(data_2d, axis=0))
print("Sum along axis 1 (rows):", np.sum(data_2d, axis=1))

print("Mean along axis 0 (column means):", np.mean(data_2d, axis=0))
print("Mean along axis 1 (row means):", np.mean(data_2d, axis=1))

print("Std along axis 0 (column std):", np.std(data_2d, axis=0))
print("Std along axis 1 (row std):", np.std(data_2d, axis=1))

# Cumulative functions
print("\n=== Cumulative Functions ===")
print("Original 1D:", data_1d)
print("Cumulative sum:", np.cumsum(data_1d))
print("Cumulative product:", np.cumprod(data_1d[:4]))  # Using subset to avoid overflow

# Sorting and related functions
print("\n=== Sorting Operations ===")
unsorted = np.array([64, 25, 12, 22, 11])
print("Original:", unsorted)
print("Sorted:", np.sort(unsorted))
print("Sort indices:", np.argsort(unsorted))
print("Unique values:", np.unique([1, 2, 2, 3, 3, 3, 4]))

# Advanced statistical functions
print("\n=== Advanced Statistics ===")
# Correlation coefficient
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
correlation_matrix = np.corrcoef(x, y)
print("Correlation coefficient between x and y:")
print(correlation_matrix)

# Covariance
covariance_matrix = np.cov(x, y)
print("Covariance matrix:")
print(covariance_matrix)

# 🧠 Linear Algebra for Machine Learning
*The mathematical foundation powering modern AI and ML algorithms*

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 20px; border-radius: 10px; color: white; text-align: center; margin: 20px 0;">
<h3 style="margin: 0; color: white;">🎯 Mathematical Powerhouse</h3>
<p style="margin: 10px 0 0 0; font-size: 1.1em; color: white;">From neural networks to dimensionality reduction - master the linear algebra that drives ML</p>
</div>

---

## 🔑 **Core Operations Matrix**

<table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
<tr style="background-color: #343a40; color: white;">
<td style="padding: 15px; border: 1px solid #495057; width: 50%; color: white;"><strong style="color: white;">🎯 Dot Product</strong><br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.dot(a, b)</code> or <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">a.dot(b)</code><br><em style="color: #bdc3c7;">Vector similarity, projections</em></td>
<td style="padding: 15px; border: 1px solid #495057; width: 50%; color: white;"><strong style="color: white;">🔄 Matrix Multiplication</strong><br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">A @ B</code> (modern, preferred)<br><em style="color: #bdc3c7;">Neural networks, transformations</em></td>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 15px; border: 1px solid #495057; color: white;"><strong style="color: white;">↔️ Matrix Inverse</strong><br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.linalg.inv()</code><br><em style="color: #bdc3c7;">Solving linear systems</em></td>
<td style="padding: 15px; border: 1px solid #495057; color: white;"><strong style="color: white;">🔢 Determinant</strong><br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.linalg.det()</code><br><em style="color: #bdc3c7;">Matrix properties, volume scaling</em></td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 15px; border: 1px solid #495057; color: white;"><strong style="color: white;">🌟 Eigenvalues</strong><br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.linalg.eig()</code><br><em style="color: #bdc3c7;">PCA, dimensionality reduction</em></td>
<td style="padding: 15px; border: 1px solid #495057; color: white;"><strong style="color: white;">⚡ Linear Systems</strong><br><code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">np.linalg.solve()</code><br><em style="color: #bdc3c7;">Linear regression, optimization</em></td>
</tr>
</table>

---

## 🎯 **Why This Matters for ML**

<div style="background-color: #2c3e50; padding: 15px; border-left: 5px solid #27ae60; margin: 15px 0; border-radius: 5px; color: white;">
<strong style="color: white;">🚀 Neural Networks:</strong> Every layer is a matrix multiplication<br>
<strong style="color: white;">📊 Linear Regression:</strong> Solved using matrix operations<br>
<strong style="color: white;">🔍 PCA:</strong> Built on eigenvalue decomposition<br>
<strong style="color: white;">📈 Optimization:</strong> Gradients computed via matrix calculus
</div>

---

In [ ]:
# Linear Algebra Operations - Foundation of ML

# Create sample matrices and vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

matrix_A = np.array([[1, 2], 
                     [3, 4]])
matrix_B = np.array([[5, 6], 
                     [7, 8]])

matrix_C = np.array([[2, 1, 3], 
                     [1, 0, 1], 
                     [1, 1, 1]])

print("Vector a:", vector_a)
print("Vector b:", vector_b)
print("Matrix A:")
print(matrix_A)
print("Matrix B:")
print(matrix_B)

# Dot Product (Vector operations)
print("\n=== Dot Product ===")
dot_product = np.dot(vector_a, vector_b)
print("Dot product (a·b):", dot_product)

# Alternative methods for dot product
print("Using @ operator:", vector_a @ vector_b)
print("Using .dot() method:", vector_a.dot(vector_b))

# Vector magnitude (norm)
print("Magnitude of vector a:", np.linalg.norm(vector_a))
print("Magnitude of vector b:", np.linalg.norm(vector_b))

# Matrix Multiplication
print("\n=== Matrix Multiplication ===")
# Method 1: @ operator (recommended)
result_at = matrix_A @ matrix_B
print("A @ B (using @ operator):")
print(result_at)

# Method 2: np.dot()
result_dot = np.dot(matrix_A, matrix_B)
print("np.dot(A, B):")
print(result_dot)

# Method 3: .dot() method
result_method = matrix_A.dot(matrix_B)
print("A.dot(B):")
print(result_method)

# Matrix-Vector multiplication
print("\n=== Matrix-Vector Multiplication ===")
mv_result = matrix_A @ np.array([1, 2])
print("Matrix A @ vector [1, 2]:", mv_result)

# Matrix properties
print("\n=== Matrix Properties ===")
print("Matrix C:")
print(matrix_C)

# Determinant
det_C = np.linalg.det(matrix_C)
print("Determinant of C:", det_C)

# Matrix inverse (only for square, non-singular matrices)
try:
    inv_C = np.linalg.inv(matrix_C)
    print("Inverse of C:")
    print(inv_C)
    
    # Verify: C @ inv(C) should be identity matrix
    identity_check = matrix_C @ inv_C
    print("C @ inv(C) (should be identity):")
    print(np.round(identity_check, 10))  # Round to handle floating point errors
except np.linalg.LinAlgError:
    print("Matrix C is singular (not invertible)")

# Transpose
print("\n=== Transpose ===")
print("Transpose of A:")
print(matrix_A.T)

# Eigenvalues and Eigenvectors (Important for PCA)
print("\n=== Eigenvalues & Eigenvectors ===")
symmetric_matrix = np.array([[4, 2], [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(symmetric_matrix)
print("Symmetric matrix:")
print(symmetric_matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

# Matrix rank
print("\n=== Matrix Rank ===")
print("Rank of matrix A:", np.linalg.matrix_rank(matrix_A))
print("Rank of matrix C:", np.linalg.matrix_rank(matrix_C))

# Trace (sum of diagonal elements)
print("Trace of matrix A:", np.trace(matrix_A))
print("Trace of matrix C:", np.trace(matrix_C))

# Solving linear systems: Ax = b
print("\n=== Solving Linear Systems ===")
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print("Solving Ax = b:")
print("A =")
print(A)
print("b =", b)
print("Solution x =", x)
print("Verification (Ax):", A @ x)

# ✨ Advanced Concepts
*Master these to write cleaner and more efficient code*

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 15px; border-radius: 8px; color: white; margin: 15px 0;">
<strong style="color: white;">🎓 Expert-Level Skills:</strong> Master these concepts to write cleaner, faster, and more elegant code
</div>

## 📡 **Broadcasting**
**The most important concept for effective NumPy use!** Broadcasting describes the rules for how NumPy performs operations on arrays of different (but compatible) shapes. Understanding broadcasting lets you avoid explicit loops, leading to highly efficient, vectorized code.

## 🧩 **Array Stacking and Splitting**
- **np.vstack()**: Stack arrays vertically (row-wise)
- **np.hstack()**: Stack arrays horizontally (column-wise)  
- **np.concatenate()**: Join a sequence of arrays along an existing axis
- **np.split()**: Split an array into multiple sub-arrays

These operations are crucial for data preprocessing and feature engineering in ML pipelines.

---

In [ ]:
# Broadcasting - The Most Important NumPy Concept!

print("=== Broadcasting Rules ===")
print("1. Start from the trailing dimension and work backward")
print("2. Dimensions are compatible if they are equal, or one of them is 1")
print("3. Missing dimensions are assumed to be 1")
print("4. If shapes are not compatible, ValueError is raised")

# Example 1: Scalar with array
print("\n=== Example 1: Scalar with Array ===")
arr = np.array([1, 2, 3, 4, 5])
scalar = 10
result = arr + scalar
print(f"Array: {arr}")
print(f"Scalar: {scalar}")
print(f"Result: {result}")
print("Broadcasting: (5,) + () → (5,)")

# Example 2: 1D array with 2D array
print("\n=== Example 2: 1D with 2D Array ===")
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
vector = np.array([10, 20, 30])
result = matrix + vector
print("Matrix (3x3):")
print(matrix)
print(f"Vector (3,): {vector}")
print("Result (3x3):")
print(result)
print("Broadcasting: (3,3) + (3,) → (3,3)")

# Example 3: Column vector with row vector
print("\n=== Example 3: Column + Row Vector ===")
col_vector = np.array([[1], [2], [3]])  # Shape: (3, 1)
row_vector = np.array([10, 20, 30])     # Shape: (3,)
result = col_vector + row_vector
print("Column vector (3x1):")
print(col_vector)
print(f"Row vector (3,): {row_vector}")
print("Result (3x3):")
print(result)
print("Broadcasting: (3,1) + (3,) → (3,3)")

# Example 4: Practical ML example - Normalizing data
print("\n=== Example 4: Data Normalization (ML Application) ===")
# Simulating a dataset with 4 samples and 3 features
data = np.array([[1, 2, 3], 
                 [4, 5, 6], 
                 [7, 8, 9], 
                 [2, 4, 6]])

print("Original data (4 samples, 3 features):")
print(data)

# Calculate mean for each feature (column)
mean = np.mean(data, axis=0)
print(f"Mean of each feature: {mean}")

# Calculate standard deviation for each feature
std = np.std(data, axis=0)
print(f"Std of each feature: {std}")

# Normalize data: (data - mean) / std
normalized_data = (data - mean) / std
print("Normalized data:")
print(normalized_data)
print("Broadcasting used: (4,3) - (3,) and (4,3) / (3,)")

# Example 5: Broadcasting with different shapes
print("\n=== Example 5: Complex Broadcasting ===")
# 3D array operations
arr_3d = np.ones((2, 3, 4))
arr_2d = np.arange(12).reshape(3, 4)
arr_1d = np.array([1, 2, 3, 4])

print("3D array shape:", arr_3d.shape)
print("2D array shape:", arr_2d.shape)
print("1D array shape:", arr_1d.shape)

# Broadcasting 3D with 2D
result_3d_2d = arr_3d + arr_2d
print("3D + 2D result shape:", result_3d_2d.shape)

# Broadcasting 3D with 1D
result_3d_1d = arr_3d + arr_1d
print("3D + 1D result shape:", result_3d_1d.shape)

# Example 6: Broadcasting errors
print("\n=== Example 6: When Broadcasting Fails ===")
try:
    incompatible_1 = np.array([[1, 2, 3]])      # Shape: (1, 3)
    incompatible_2 = np.array([[1], [2]])       # Shape: (2, 1)
    # This will fail because 3 and 2 are not compatible
    result = incompatible_1 + incompatible_2
except ValueError as e:
    print(f"Broadcasting error: {e}")
    print("Shapes (1,3) and (2,1) are not compatible")
    print("3 ≠ 1 and 1 ≠ 2, so broadcasting fails")

# Practical tips
print("\n=== Broadcasting Tips ===")
print("1. Use reshape() to add dimensions: arr.reshape(-1, 1) for column vector")
print("2. Use np.newaxis to add dimensions: arr[:, np.newaxis]")
print("3. Visualize shapes mentally or use .shape to debug")

# Demonstrating newaxis
print("\n=== Using np.newaxis ===")
vector = np.array([1, 2, 3])
print(f"Original vector shape: {vector.shape}")
col_vector = vector[:, np.newaxis]
print(f"Column vector shape: {col_vector.shape}")
row_vector = vector[np.newaxis, :]
print(f"Row vector shape: {row_vector.shape}")

In [ ]:
# Array Stacking and Splitting - Essential for Data Preprocessing

# Create sample arrays for demonstration
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
vector3 = np.array([7, 8, 9])

print("Sample arrays:")
print("arr1:")
print(arr1)
print("arr2:")
print(arr2)
print("arr3:")
print(arr3)

# Vertical Stacking (vstack)
print("\n=== Vertical Stacking (vstack) ===")
v_stacked = np.vstack([arr1, arr2, arr3])
print("np.vstack([arr1, arr2, arr3]):")
print(v_stacked)
print("Shape:", v_stacked.shape)

# Alternative: concatenate with axis=0
v_concat = np.concatenate([arr1, arr2, arr3], axis=0)
print("Using concatenate (axis=0) - same result:")
print(v_concat)

# Horizontal Stacking (hstack)
print("\n=== Horizontal Stacking (hstack) ===")
h_stacked = np.hstack([arr1, arr2, arr3])
print("np.hstack([arr1, arr2, arr3]):")
print(h_stacked)
print("Shape:", h_stacked.shape)

# Alternative: concatenate with axis=1
h_concat = np.concatenate([arr1, arr2, arr3], axis=1)
print("Using concatenate (axis=1) - same result:")
print(h_concat)

# Stacking 1D arrays
print("\n=== Stacking 1D Arrays ===")
print("Vectors:", vector1, vector2, vector3)

# Vertical stacking creates 2D array (rows)
v_stack_1d = np.vstack([vector1, vector2, vector3])
print("vstack 1D vectors:")
print(v_stack_1d)
print("Shape:", v_stack_1d.shape)

# Horizontal stacking concatenates into longer 1D array
h_stack_1d = np.hstack([vector1, vector2, vector3])
print("hstack 1D vectors:")
print(h_stack_1d)
print("Shape:", h_stack_1d.shape)

# Column stacking (creates 2D array with vectors as columns)
print("\n=== Column Stacking ===")
column_stacked = np.column_stack([vector1, vector2, vector3])
print("np.column_stack([vector1, vector2, vector3]):")
print(column_stacked)
print("Shape:", column_stacked.shape)

# Row stacking (alias for vstack)
row_stacked = np.row_stack([vector1, vector2, vector3])
print("np.row_stack([vector1, vector2, vector3]):")
print(row_stacked)

# 3D stacking
print("\n=== 3D Stacking ===")
# Stack along a new axis (depth-wise)
depth_stacked = np.stack([arr1, arr2, arr3], axis=0)
print("np.stack along axis=0 (depth):")
print("Shape:", depth_stacked.shape)
print("First slice:")
print(depth_stacked[0])

# Stack along different axes
width_stacked = np.stack([arr1, arr2], axis=1)
print("np.stack along axis=1 (width):")
print("Shape:", width_stacked.shape)

height_stacked = np.stack([arr1, arr2], axis=2)
print("np.stack along axis=2 (height):")
print("Shape:", height_stacked.shape)

# Array Splitting
print("\n=== Array Splitting ===")
large_array = np.arange(12).reshape(4, 3)
print("Original array to split:")
print(large_array)
print("Shape:", large_array.shape)

# Vertical split (split rows)
print("\n--- Vertical Split (vsplit) ---")
v_split_result = np.vsplit(large_array, 2)  # Split into 2 parts
print("np.vsplit(array, 2):")
for i, part in enumerate(v_split_result):
    print(f"Part {i}:")
    print(part)

# Horizontal split (split columns)
print("\n--- Horizontal Split (hsplit) ---")
h_split_result = np.hsplit(large_array, 3)  # Split into 3 parts
print("np.hsplit(array, 3):")
for i, part in enumerate(h_split_result):
    print(f"Part {i}:")
    print(part)

# Split at specific indices
print("\n--- Split at Specific Indices ---")
indices_split = np.split(large_array, [1, 3], axis=0)  # Split after row 0 and row 2
print("np.split(array, [1, 3], axis=0):")
for i, part in enumerate(indices_split):
    print(f"Part {i}:")
    print(part)

# Practical ML example: Train/Validation/Test split
print("\n=== ML Application: Data Splitting ===")
# Simulate a dataset
dataset = np.random.rand(1000, 5)  # 1000 samples, 5 features
print(f"Dataset shape: {dataset.shape}")

# Split into train (60%), validation (20%), test (20%)
train_size = int(0.6 * len(dataset))
val_size = int(0.2 * len(dataset))

train_data = dataset[:train_size]
val_data = dataset[train_size:train_size + val_size]
test_data = dataset[train_size + val_size:]

print(f"Training set shape: {train_data.shape}")
print(f"Validation set shape: {val_data.shape}")
print(f"Test set shape: {test_data.shape}")

# Alternative using array_split for equal-ish parts
equal_splits = np.array_split(dataset, 5)  # Split into 5 roughly equal parts
print(f"Equal splits shapes: {[part.shape for part in equal_splits]}")

# Combining operations: Feature engineering example
print("\n=== Feature Engineering Example ===")
# Create some sample features
feature1 = np.random.rand(100, 1)
feature2 = np.random.rand(100, 1) 
feature3 = np.random.rand(100, 1)

# Combine features horizontally
combined_features = np.hstack([feature1, feature2, feature3])
print(f"Combined features shape: {combined_features.shape}")

# Add polynomial features (feature interactions)
feature1_squared = feature1 ** 2
feature1_times_feature2 = feature1 * feature2

# Stack all features
final_features = np.hstack([combined_features, feature1_squared, feature1_times_feature2])
print(f"Final feature matrix shape: {final_features.shape}")
print("Original 3 features expanded to 5 features with polynomial terms")

# 🎯 NumPy Mastery: Your ML Foundation Complete!
*Congratulations! You've mastered the essential library that powers the entire Python data science ecosystem*

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 30px; border-radius: 15px; color: white; text-align: center; margin: 30px 0;">
<h2 style="margin: 0; color: white;">🏆 Achievement Unlocked</h2>
<p style="margin: 15px 0 0 0; font-size: 1.2em; font-weight: bold; color: white;">NumPy Expert Status Achieved!</p>
<p style="margin: 10px 0 0 0; font-size: 1em; color: white;">Ready to tackle pandas, scikit-learn, TensorFlow, and beyond</p>
</div>

---

## 🎓 **Skills Mastered**

### 🔧 **Data Manipulation & Indexing**
<div style="background-color: #2c3e50; padding: 15px; border-radius: 8px; margin: 10px 0; color: white;">
<strong style="color: white;">✅ Boolean indexing</strong> - Your best friend for data filtering<br>
<strong style="color: white;">✅ Fancy indexing</strong> - Complex data selection patterns<br>
<strong style="color: white;">✅ Advanced slicing</strong> - Efficient data subsetting<br>
<strong style="color: white;">✅ Reshaping mastery</strong> - Preparing data for ML algorithms
</div>

### 📈 **Mathematical Operations**
<div style="background-color: #2c3e50; padding: 15px; border-radius: 8px; margin: 10px 0; color: white;">
<strong style="color: white;">✅ Vectorized operations</strong> - 10-100x faster than Python loops<br>
<strong style="color: white;">✅ Universal functions</strong> - Element-wise mathematical operations<br>
<strong style="color: white;">✅ Statistical analysis</strong> - Data exploration and feature engineering<br>
<strong style="color: white;">✅ Aggregation functions</strong> - Summarizing and analyzing datasets
</div>

### 🧠 **Linear Algebra**
<div style="background-color: #2c3e50; padding: 15px; border-radius: 8px; margin: 10px 0; color: white;">
<strong style="color: white;">✅ Matrix operations</strong> - Foundation of neural networks<br>
<strong style="color: white;">✅ Eigenvalue decomposition</strong> - Essential for PCA and dimensionality reduction<br>
<strong style="color: white;">✅ Linear system solving</strong> - Core of linear regression<br>
<strong style="color: white;">✅ Advanced matrix properties</strong> - Determinants, inverses, and more
</div>

### ✨ **Advanced Techniques**
<div style="background-color: #2c3e50; padding: 15px; border-radius: 8px; margin: 10px 0; color: white;">
<strong style="color: white;">✅ Broadcasting mastery</strong> - Elegant vectorized code without loops<br>
<strong style="color: white;">✅ Array manipulation</strong> - Stacking, splitting, and preprocessing<br>
<strong style="color: white;">✅ Memory optimization</strong> - Views vs copies for efficient computing<br>
<strong style="color: white;">✅ Performance optimization</strong> - Writing fast, efficient NumPy code
</div>

---

## 🚀 **Your ML Journey Continues**

<table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
<tr style="background-color: #343a40; color: white;">
<th style="padding: 15px; border: 1px solid #495057; text-align: left; color: white;">Next Steps</th>
<th style="padding: 15px; border: 1px solid #495057; text-align: left; color: white;">Build Upon NumPy</th>
</tr>
<tr style="background-color: #2c3e50; color: white;">
<td style="padding: 15px; border: 1px solid #495057; width: 50%; color: white;">
<strong style="color: white;">📊 Pandas</strong><br>
<em style="color: #bdc3c7;">DataFrames built on NumPy arrays</em><br>
<small style="color: #bdc3c7;">Data cleaning, manipulation, analysis</small>
</td>
<td style="padding: 15px; border: 1px solid #495057; width: 50%; color: white;">
<strong style="color: white;">📈 Matplotlib/Seaborn</strong><br>
<em style="color: #bdc3c7;">Visualization with NumPy backend</em><br>
<small style="color: #bdc3c7;">Create stunning data visualizations</small>
</td>
</tr>
<tr style="background-color: #343a40; color: white;">
<td style="padding: 15px; border: 1px solid #495057; color: white;">
<strong style="color: white;">🤖 Scikit-learn</strong><br>
<em style="color: #bdc3c7;">ML algorithms using NumPy</em><br>
<small style="color: #bdc3c7;">Classification, regression, clustering</small>
</td>
<td style="padding: 15px; border: 1px solid #495057; color: white;">
<strong style="color: white;">🧠 TensorFlow/PyTorch</strong><br>
<em style="color: #bdc3c7;">Deep learning with NumPy-like syntax</em><br>
<small style="color: #bdc3c7;">Neural networks and AI models</small>
</td>
</tr>
</table>

---

## 💡 **Best Practices Checklist**

<div style="background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%); padding: 20px; border-radius: 10px; color: white; margin: 20px 0;">
<h4 style="margin: 0; color: white;">🎯 Remember These Golden Rules:</h4>
<div style="margin: 15px 0; color: white;">
<strong style="color: white;">⚡ Always vectorize:</strong> Avoid Python loops when possible<br>
<strong style="color: white;">📡 Master broadcasting:</strong> Key to writing efficient NumPy code<br>
<strong style="color: white;">🧠 Choose right data types:</strong> Consider memory usage with large datasets<br>
<strong style="color: white;">📊 Profile your code:</strong> Use <code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">%timeit</code> to optimize performance<br>
<strong style="color: white;">🔧 Leverage linear algebra:</strong> Most ML algorithms have NumPy implementations
</div>
</div>

---

## 🏁 **Final Challenge**

<div style="background-color: #2c3e50; padding: 20px; border-left: 5px solid #95a5a6; margin: 20px 0; border-radius: 5px; text-align: center; color: white;">
<strong style="color: white;">🎯 Put your skills to the test!</strong><br>
<em style="color: #bdc3c7;">Try implementing a simple neural network forward pass using only NumPy</em><br>
<code style="background-color: #34495e; color: white; padding: 2px 4px; border-radius: 3px;">output = activation(input @ weights + bias)</code><br>
<small style="color: #bdc3c7;">You now have all the tools you need! 🚀</small>
</div>

---

<div style="text-align: center; margin: 30px 0;">
<h3 style="color: white;">🎉 Congratulations on mastering NumPy! 🎉</h3>
<p style="font-size: 1.1em; color: #bdc3c7;"><em>You're now ready to tackle any data science or machine learning challenge with confidence!</em></p>
</div>